# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating a simple array
arr = np.arange(0,11)

In [3]:
#show
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


#  Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index 8
arr[8]

8

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

#  Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [7]:
#Setting a value with index range (Broadcasting)
arr[1:5]=100  #Setting the value 100 from 1 to 4th index (including both)..

In [8]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Important notes on Slices
slice_of_arr = arr[0:6]  #Creating a new array from 0th index to the 5th index(including both).

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
#Change slice..
slice_of_arr[:] = 99  #this will convert each and every value to 99..

In [12]:
#show the array.
slice_of_arr

array([99, 99, 99, 99, 99, 99])

**Now note the changes also occur in our original array!**

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Data is not copied, it's a view of the original array! This avoids memory problems!**

In [15]:
#When you want to create a copy of the array..(.copy() function is used.)
arr_cpy = arr.copy()

In [16]:
#Show the copy array.
arr_cpy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [19]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))  #bracket inside brackets.

In [22]:
#show the array.
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#indexing the row..
arr_2d[1]  #this will retrieve the first row..from the 2D array

array([4, 5, 6])

In [28]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][1]  #extracting the value present at the first row and first column..

5

In [29]:
arr_2d[1][0]  #first row and 0th column..

4

In [30]:
# Getting individual element value
arr_2d[1,0]


#You can use both the methods..to extract a particular value..from the 2D matrix.

4

In [37]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,:1]  #first two rows and its first element..

array([[1],
       [4]])

In [38]:
#Shape bottom row
arr_2d[2]  #It will access the second row..

array([7, 8, 9])

In [39]:
#Shape bottom row
arr_2d[2,:]

array([7, 8, 9])

#  Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [43]:
#Set up matrix
arr2d = np.zeros((10,10))  #make a matrix of 10-rows and 10-columns..

#show the matrix
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
#Length of array
arr_length = arr2d.shape[1]  #it will return the length of the first row of the matrix..which is 10..

#show the length
arr_length

10

In [49]:
#Set up array
for i in range(arr_length):  #set each row with the value from [0-9]..
    arr2d[i]=i

#show the updated matrix
arr2d    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [51]:
arr2d[[2,4,6,8]]  #It returns 2nd,4th,6th and 8th row from the 2D matrix..

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [53]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. 

## Selection

Let's briefly go over how to use brackets for selection based on comparison operators.

In [56]:
arr = np.arange(0,11)

#show the array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
#Now using some of the comparision operator..
arr>4 

#You will be able to see the boolean values...(True for the values which satisfies the condition and false for the values
#which won't)..

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [65]:
#storing the above answer in an array.
bool_arr = arr>4

#show the array
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [66]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [67]:
arr[bool_arr] #this will return the values from the array..(which are true.)

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>2]  #this will return the values from the array whose value is greater than 2..

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
x=2
arr[arr>x]  #same with this case too..

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job